site_name: PyPythia
site_description: Lightweight Python library for predicting the difficulty of phylogenetic alignments
site_url: https://tschuelia.github.io/PyPythia/
repo_name: tschuelia/PyPythia
repo_url: https://github.com/tschuelia/PyPythia
edit_uri: edit/master/docs/
docs_dir: docs
site_dir: site
remote_name: origin
remote_branch: gh-pages

extra:
  version:
    provider: mike
    default: latest

markdown_extensions:
- def_list
- github-callouts

nav:
- Home: index.md
- Install: install.md
- User Guide: usage.md
- API Reference:
  - msa: api/msa.md
  - raxmlng: api/raxmlng.md
  - prediction: api/prediction.md
  - predictor: api/predictor.md
  - custom_types: api/custom_types.md
  - custom_errors: api/custom_errors.md
  - config: api/config.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - .
- mike:
    canonical_version: latest

theme:
  name: material
  palette:
  - media: (prefers-color-scheme)
    scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/lightbulb-auto-outline
      name: Switch to system preference
